CC     = mpicc
CFLAGS = -g -O3
LDLIBS = -lm

#CFLAGS += -finstrument-functions

OBJS =  cfg.o\
	cloneMates.o\
	dynamic.o\
	err.o\
	est.o\
	keys.o\
	master.o\
	mastercode.o\
	stree.o\
	suff.o\
	uFind.o\

all: PaCE

pf: $(OBJS) pf.o
	gcc -c pf.c -o pf.o
	$(CC) $(OBJS) pf.o -o PaCE_pf $(LDLIBS)


PaCE: $(OBJS)
	$(CC) $(OBJS) -o PaCE $(LDLIBS)

clean:
	rm -f *.o PaCE PaCE_pf
